// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulnmenrgxlecqpmgswxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsbm1lbnJneGxlY3FwbWdzd3hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTMyMTcsImV4cCI6MjA2MDU4OTIxN30.WRFwLBB1EHWesfavxPeeLcaKFZ9WfGl_6O5TnQD2wEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);